# Generated by Django 2.2.5 on 2019-09-22 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grabit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('is_worthy', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
